version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ktor_postgres
    restart: always
    environment:
      POSTGRES_USER: ktor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ktor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
